name: xm_util
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0
  app_links: ^6.4.1
  fluwx: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/doc/

fluwx:
  app_id: wxd96f9ed754396015
  debug_logging: true # Logging in debug mode.
  android:
    interrupt_wx_request: true # Defaults to true.
    flutter_activity: "MainActivity" # Defaults to app's launcher
  ios:
    universal_link: https://
    scene_delegate: false # Defaults to false.
    no_pay: true # Set to true to disable payment.
    ignore_security: true # Set to true to disable security seetings.
